[manifest]
version = "0.1.0"
priority = 0


## Secret Tag sound


[[patches]]
[patches.pattern]
target = 'tag.lua'
pattern = '''
play_sound('paper1', math.random()*0.1 + 0.55, 0.42)
'''
position = "before"
payload = '''
if self.key == "tag_nancy_secret" then
    play_sound("voice"..math.random(11), 1, 0.4)
end
'''
match_indent = true