[manifest]
version = "0.1.0"
priority = 0


## Velvet Purse implementation


[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
-- TARGET: adding to hand effects
'''
position = "after"
payload = '''
if next(SMODS.find_card("v_nancy_purse")) then
    for _, _card in ipairs(G.hand.cards) do
        if _card.edition and _card.edition.key == "e_negative" then table.insert(final_scoring_hand, _card) end
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
SMODS.calculate_main_scoring({cardarea = v, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, v == G.play and scoring_hand or nil)
'''
position = "at"
payload = '''
if next(SMODS.find_card("v_nancy_purse")) then
    SMODS.calculate_main_scoring({cardarea = v, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, (v == G.play or v == G.hand) and scoring_hand or nil)
    if v == G.hand then SMODS.calculate_main_scoring({cardarea = v, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, v == G.play and scoring_hand or nil) end
else
    SMODS.calculate_main_scoring({cardarea = v, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, v == G.play and scoring_hand or nil)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
SMODS.calculate_destroying_cards({ full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, cardarea = v }, cards_destroyed, v == G.play and scoring_hand or nil)
'''
position = "at"
payload = '''
if next(SMODS.find_card("v_nancy_purse")) then
    SMODS.calculate_destroying_cards({ full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, cardarea = v }, cards_destroyed, (v == G.play or v == G.hand) and scoring_hand or nil)
    if v == G.hand then SMODS.calculate_destroying_cards({ full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, cardarea = v }, cards_destroyed, v == G.play and scoring_hand or nil) end
else
    SMODS.calculate_destroying_cards({ full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, cardarea = v }, cards_destroyed, v == G.play and scoring_hand or nil)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
-- TARGET: effects after hand debuffed by blind
'''
position = "after"
payload = '''
if next(SMODS.find_card("v_nancy_purse")) then
    for i=1, #scoring_hand do
        highlight_card(scoring_hand[i],(i-0.999)/5,'down')
    end
end
'''
match_indent = true